# Generated by Django 4.0.1 on 2022-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceName',
            new_name='devicename',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_Technician',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='myimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
