# Generated by Django 4.0.1 on 2022-01-13 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0008_alter_customuser_is_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordertechnician', to='project_user.technician', verbose_name='technician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Feedback Giver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technician',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
