# Generated by Django 4.0.1 on 2022-01-13 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0009_order_technician_alter_feedback_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
